name: autofix.ci

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - bun.lock

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dependabot-bun-dedupe:
    uses: stella/.github/.github/workflows/dependabot-bun-dedupe.yml@437d9d78c38114a15c368daed7d3d1b36fd6b8fc
