name: autofix.ci

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - bun.lock

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dependabot-bun-dedupe:
    uses: stella/.github/.github/workflows/dependabot-bun-dedupe.yml@9e1915536efc226c5ec9d3ca0f2192be5aa6ec7e
