name: Provenance Nightly

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  provenance-update:
    permissions:
      contents: write
      pull-requests: write
    uses: stella/.github/.github/workflows/provenance-update.yml@9e1915536efc226c5ec9d3ca0f2192be5aa6ec7e
    secrets: inherit
    with:
      install-command: bun install --frozen-lockfile
      provenance-version: v0.1.3
