name: Provenance Nightly

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  provenance-update:
    permissions:
      contents: write
      pull-requests: write
    uses: stella/.github/.github/workflows/provenance-update.yml@437d9d78c38114a15c368daed7d3d1b36fd6b8fc
    secrets: inherit
    with:
      install-command: bun install --frozen-lockfile
      provenance-version: v0.1.3
